# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tdcursos.github.io" # the base hostname & protocol for your site, e.g. https://USERNAME.github.io

# Change to your lang - This doesn't translate the theme, it just defines the main language the content is written in.
lang: pt-BR

timezone: America/Belem # Change to your timezone - https://kevinnovak.github.io/Time-Zone-Picker/

title: Joana Doe
tagline: Web Design
description: A beautiful description for your blog/website.
avatar: "assets/img/avatar/avatar.webp" # The avatar on sidebar

# Social profiles
email: youremail@domain.com
github: elainefs
linkedin: elaineferreiras
mastodon:
  instance: mastodon.social
  user: elainefs

# Url for you account: Buy Me A Coffee, Ko-fi, Patreon, etc.
donate:

# License - eg: Copyright, CC BY-NC-SA 4.0, etc.
license: CC BY-NC-SA 4.0
licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt-br"

# Build settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options - https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6

jekyll-minifier:
  exclude: "atom.xml" # Exclude files from processing
  uglifier_args:
    harmony: true

defaults:
  - scope:
      path: ""
    values:
      toc: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title
      image:
        path: ""
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: pages
    values:
      layout: "page"

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

include:
  - _pages
